name: StadiaMaps
targets:
  StadiaMaps:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [Sources]
    info:
      path: ./Info.plist
      version: 5.0.6
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
