//
// AddendumV2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** Miscellaneous data that doesn&#39;t quite fit anywhere else in the record. */
public struct AddendumV2: Codable, JSONEncodable, Hashable {
    public var foursquare: FoursquareAddendum?
    public var geonames: GeonamesAddendum?
    public var osm: OpenStreetMapAddendum?
    public var whosonfirstConcordances: WhosOnFirstConcordances?

    public init(foursquare: FoursquareAddendum? = nil, geonames: GeonamesAddendum? = nil, osm: OpenStreetMapAddendum? = nil, whosonfirstConcordances: WhosOnFirstConcordances? = nil) {
        self.foursquare = foursquare
        self.geonames = geonames
        self.osm = osm
        self.whosonfirstConcordances = whosonfirstConcordances
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case foursquare
        case geonames
        case osm
        case whosonfirstConcordances = "whosonfirst_concordances"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(foursquare, forKey: .foursquare)
        try container.encodeIfPresent(geonames, forKey: .geonames)
        try container.encodeIfPresent(osm, forKey: .osm)
        try container.encodeIfPresent(whosonfirstConcordances, forKey: .whosonfirstConcordances)
    }
}
