//
// AnnotationFilters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct AnnotationFilters: Codable, JSONEncodable, Hashable {
    public enum Action: String, Codable, CaseIterable {
        case include
        case exclude
    }

    public enum Attributes: String, Codable, CaseIterable {
        case speed = "shape_attributes.speed"
        case speedLimit = "shape_attributes.speed_limit"
        case time = "shape_attributes.time"
        case length = "shape_attributes.length"
    }

    public var action: Action?
    /** A set of granular attributes to include between every pair of coordinates along the route. This can significantly increase the response size. */
    public var attributes: [Attributes]?

    public init(action: Action? = nil, attributes: [Attributes]? = nil) {
        self.action = action
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}
