//
// BaseCostingOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct BaseCostingOptions: Codable, JSONEncodable, Hashable {
    public static let useLivingStreetsRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public static let useFerryRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public static let useRailFerryRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    /** A penalty (in seconds) applied when transitioning between roads (determined by name). */
    public var maneuverPenalty: Int? = 5
    /** The estimated cost (in seconds) when a gate is encountered. */
    public var gateCost: Int? = 15
    /** A penalty (in seconds) applied to the route cost when a gate is encountered. This penalty can be used to reduce the likelihood of suggesting a route with gates unless absolutely necessary. */
    public var gatePenalty: Int? = 300
    /** The estimated cost (in seconds) when encountering an international border. */
    public var countryCrossingCost: Int? = 600
    /** A penalty applied to transitions to international border crossings. This penalty can be used to reduce the likelihood of suggesting a route with border crossings unless absolutely necessary. */
    public var countryCrossingPenalty: Int? = 0
    /** A penalty applied to transitions to service roads. This penalty can be used to reduce the likelihood of suggesting a route with service roads unless absolutely necessary. The default penalty is 15 for cars, busses, motor scooters, and motorcycles; and zero for others. */
    public var servicePenalty: Int?
    /** A factor that multiplies the cost when service roads are encountered. The default is 1.2 for cars and busses, and 1 for trucks, motor scooters, and motorcycles. */
    public var serviceFactor: Double? = 1
    /** A measure of willingness to take living streets. Values near 0 attempt to avoid them, and values near 1 will favour them. Note that as some routes may be impossible without living streets, 0 does not guarantee avoidance of them. The default value is 0 for trucks; 0.1 for other motor vehicles; 0.5 for bicycles; and 0.6 for pedestrians. */
    public var useLivingStreets: Double?
    /** A measure of willingness to take ferries. Values near 0 attempt to avoid ferries, and values near 1 will favour them. Note that as some routes may be impossible without ferries, 0 does not guarantee avoidance of them. */
    public var useFerry: Double? = 0.5
    /** If set to true, ignores any restrictions (eg: turn and conditional restrictions). Useful for matching GPS traces to the road network regardless of restrictions. */
    public var ignoreRestrictions: Bool?
    /** If set to true, ignores most restrictions (eg: turn and conditional restrictions), but still respects restrictions that impact vehicle safety such as weight and size. */
    public var ignoreNonVehicularRestrictions: Bool?
    /** If set to true, ignores directional restrictions on roads. Useful for matching GPS traces to the road network regardless of restrictions. */
    public var ignoreOneways: Bool?
    /** A penalty (in seconds) for accessing private roads. */
    public var privateAccessPenalty: Double? = 450
    /** A penalty (in seconds) for using alleys. */
    public var alleyPenalty: Double?
    /** The estimated cost (in seconds) when a rail ferry is encountered. Only applies to costing models that support rail ferries (auto, truck, motorcycle). */
    public var railFerryCost: Int? = 300
    /** A measure of willingness to take rail ferries. Values near 0 attempt to avoid rail ferries, and values near 1 will favor them. Note that as some routes may be impossible without rail ferries, 0 does not guarantee avoidance of them. Only applies to auto, truck, and motorcycle costing. */
    public var useRailFerry: Double? = 0.4
    /** If set to true, ignores access restrictions for the route. */
    public var ignoreAccess: Bool? = false
    /** The estimated cost (in seconds) when a ferry is encountered. */
    public var ferryCost: Int? = 300

    public init(maneuverPenalty: Int? = 5, gateCost: Int? = 15, gatePenalty: Int? = 300, countryCrossingCost: Int? = 600, countryCrossingPenalty: Int? = 0, servicePenalty: Int? = nil, serviceFactor: Double? = 1, useLivingStreets: Double? = nil, useFerry: Double? = 0.5, ignoreRestrictions: Bool? = nil, ignoreNonVehicularRestrictions: Bool? = nil, ignoreOneways: Bool? = nil, privateAccessPenalty: Double? = 450, alleyPenalty: Double? = nil, railFerryCost: Int? = 300, useRailFerry: Double? = 0.4, ignoreAccess: Bool? = false, ferryCost: Int? = 300) {
        self.maneuverPenalty = maneuverPenalty
        self.gateCost = gateCost
        self.gatePenalty = gatePenalty
        self.countryCrossingCost = countryCrossingCost
        self.countryCrossingPenalty = countryCrossingPenalty
        self.servicePenalty = servicePenalty
        self.serviceFactor = serviceFactor
        self.useLivingStreets = useLivingStreets
        self.useFerry = useFerry
        self.ignoreRestrictions = ignoreRestrictions
        self.ignoreNonVehicularRestrictions = ignoreNonVehicularRestrictions
        self.ignoreOneways = ignoreOneways
        self.privateAccessPenalty = privateAccessPenalty
        self.alleyPenalty = alleyPenalty
        self.railFerryCost = railFerryCost
        self.useRailFerry = useRailFerry
        self.ignoreAccess = ignoreAccess
        self.ferryCost = ferryCost
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maneuverPenalty = "maneuver_penalty"
        case gateCost = "gate_cost"
        case gatePenalty = "gate_penalty"
        case countryCrossingCost = "country_crossing_cost"
        case countryCrossingPenalty = "country_crossing_penalty"
        case servicePenalty = "service_penalty"
        case serviceFactor = "service_factor"
        case useLivingStreets = "use_living_streets"
        case useFerry = "use_ferry"
        case ignoreRestrictions = "ignore_restrictions"
        case ignoreNonVehicularRestrictions = "ignore_non_vehicular_restrictions"
        case ignoreOneways = "ignore_oneways"
        case privateAccessPenalty = "private_access_penalty"
        case alleyPenalty = "alley_penalty"
        case railFerryCost = "rail_ferry_cost"
        case useRailFerry = "use_rail_ferry"
        case ignoreAccess = "ignore_access"
        case ferryCost = "ferry_cost"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maneuverPenalty, forKey: .maneuverPenalty)
        try container.encodeIfPresent(gateCost, forKey: .gateCost)
        try container.encodeIfPresent(gatePenalty, forKey: .gatePenalty)
        try container.encodeIfPresent(countryCrossingCost, forKey: .countryCrossingCost)
        try container.encodeIfPresent(countryCrossingPenalty, forKey: .countryCrossingPenalty)
        try container.encodeIfPresent(servicePenalty, forKey: .servicePenalty)
        try container.encodeIfPresent(serviceFactor, forKey: .serviceFactor)
        try container.encodeIfPresent(useLivingStreets, forKey: .useLivingStreets)
        try container.encodeIfPresent(useFerry, forKey: .useFerry)
        try container.encodeIfPresent(ignoreRestrictions, forKey: .ignoreRestrictions)
        try container.encodeIfPresent(ignoreNonVehicularRestrictions, forKey: .ignoreNonVehicularRestrictions)
        try container.encodeIfPresent(ignoreOneways, forKey: .ignoreOneways)
        try container.encodeIfPresent(privateAccessPenalty, forKey: .privateAccessPenalty)
        try container.encodeIfPresent(alleyPenalty, forKey: .alleyPenalty)
        try container.encodeIfPresent(railFerryCost, forKey: .railFerryCost)
        try container.encodeIfPresent(useRailFerry, forKey: .useRailFerry)
        try container.encodeIfPresent(ignoreAccess, forKey: .ignoreAccess)
        try container.encodeIfPresent(ferryCost, forKey: .ferryCost)
    }
}
