//
// BulkSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct BulkSearchResponse: Codable, JSONEncodable, Hashable {
    public var status: Int
    public var response: PeliasResponse?
    /** An error message describing what went wrong (if the status is not 200). */
    public var msg: String?

    public init(status: Int, response: PeliasResponse? = nil, msg: String? = nil) {
        self.status = status
        self.response = response
        self.msg = msg
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case response
        case msg
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(response, forKey: .response)
        try container.encodeIfPresent(msg, forKey: .msg)
    }
}
