//
// BulkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct BulkRequest: Codable, JSONEncodable, Hashable {
    public enum Endpoint: String, Codable, CaseIterable {
        case slashV1SlashSearch = "/v1/search"
        case slashV1SlashSearchSlashStructured = "/v1/search/structured"
        case slashV1SlashReverse = "/v1/reverse"
    }

    public var endpoint: Endpoint
    public var query: BulkRequestQuery

    public init(endpoint: Endpoint, query: BulkRequestQuery) {
        self.endpoint = endpoint
        self.query = query
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpoint
        case query
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(endpoint, forKey: .endpoint)
        try container.encode(query, forKey: .query)
    }
}
