//
// BulkRequestQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public enum BulkRequestQuery: Codable, JSONEncodable, Hashable {
    case typeSearchQuery(SearchQuery)
    case typeSearchStructuredQuery(SearchStructuredQuery)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case let .typeSearchQuery(value):
            try container.encode(value)
        case let .typeSearchStructuredQuery(value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(SearchQuery.self) {
            self = .typeSearchQuery(value)
        } else if let value = try? container.decode(SearchStructuredQuery.self) {
            self = .typeSearchStructuredQuery(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of BulkRequestQuery"))
        }
    }
}
