//
// BulkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public enum BulkRequest: Codable, JSONEncodable, Hashable {
    case typeSearchBulkQuery(SearchBulkQuery)
    case typeSearchStructuredBulkQuery(SearchStructuredBulkQuery)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case let .typeSearchBulkQuery(value):
            try container.encode(value)
        case let .typeSearchStructuredBulkQuery(value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(SearchBulkQuery.self) {
            self = .typeSearchBulkQuery(value)
        } else if let value = try? container.decode(SearchStructuredBulkQuery.self) {
            self = .typeSearchStructuredBulkQuery(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of BulkRequest"))
        }
    }
}
