//
// CostingModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** A model which influences the routing based on the type of travel. The costing model affects parameters ranging from which roads are legally accessible to preferences based on comfort or speed. See https://valhalla.github.io/valhalla/api/turn-by-turn/api-reference/#costing-models for in-depth descriptions of each costing model. */
public enum CostingModel: String, Codable, CaseIterable {
    case auto
    case bus
    case taxi
    case truck
    case bicycle
    case bikeshare
    case motorScooter = "motor_scooter"
    case motorcycle
    case pedestrian
    case lowSpeedVehicle = "low_speed_vehicle"
}
