//
// EdgeUse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The use for the edge. */
public enum EdgeUse: String, Codable, CaseIterable {
    case road = "road"
    case ramp = "ramp"
    case turnChannel = "turn_channel"
    case track = "track"
    case driveway = "driveway"
    case alley = "alley"
    case parkingAisle = "parking_aisle"
    case emergencyAccess = "emergency_access"
    case driveThrough = "drive_through"
    case culdesac = "culdesac"
    case livingStreet = "living_street"
    case serviceRoad = "service_road"
    case cycleway = "cycleway"
    case mountainBike = "mountain_bike"
    case sidewalk = "sidewalk"
    case footway = "footway"
    case steps = "steps"
    case path = "path"
    case pedestrian = "pedestrian"
    case pedestrianCrossing = "pedestrian_crossing"
    case bridleway = "bridleway"
    case restArea = "rest_area"
    case serviceArea = "service_area"
    case other = "other"
    case ferry = "ferry"
    case railFerry = "rail-ferry"
    case rail = "rail"
    case bus = "bus"
    case egressConnection = "egress_connection"
    case platformConnection = "platform_connection"
    case transitConnection = "transit_connection"
}
