//
// FeaturePropertiesV2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct FeaturePropertiesV2: Codable, JSONEncodable, Hashable {
    public static let bboxRule = ArrayRule(minItems: 4, maxItems: 4, uniqueItems: false)
    public var bbox: [Double]?
    public var geometry: Point?
    public var properties: FeaturePropertiesV2Properties
    public var type: String?

    public init(bbox: [Double]? = nil, geometry: Point? = nil, properties: FeaturePropertiesV2Properties, type: String? = nil) {
        self.bbox = bbox
        self.geometry = geometry
        self.properties = properties
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bbox
        case geometry
        case properties
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bbox, forKey: .bbox)
        try container.encodeIfPresent(geometry, forKey: .geometry)
        try container.encode(properties, forKey: .properties)
        try container.encodeIfPresent(type, forKey: .type)
    }
}
