//
// GeocodingMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct GeocodingMeta: Codable, JSONEncodable, Hashable {
    public var attribution: String
    /** Errors encountered serving the request (if any). */
    public var error: String?

    public init(attribution: String, error: String? = nil) {
        self.attribution = attribution
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attribution
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attribution, forKey: .attribution)
        try container.encodeIfPresent(error, forKey: .error)
    }
}
