//
// GeonamesAddendum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct GeonamesAddendum: Codable, JSONEncodable, Hashable {
    /** The GeoNames feature code (for GeoNames results only). */
    public var featureCode: String

    public init(featureCode: String) {
        self.featureCode = featureCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case featureCode = "feature_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(featureCode, forKey: .featureCode)
    }
}
