//
// IsochroneCostingModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public enum IsochroneCostingModel: String, Codable, CaseIterable {
    case auto
    case autoTraffic = "auto_traffic"
    case autoTrafficPremium = "auto_traffic_premium"
    case bus
    case busTraffic = "bus_traffic"
    case busTrafficPremium = "bus_traffic_premium"
    case taxi
    case taxiTraffic = "taxi_traffic"
    case taxiTrafficPremium = "taxi_traffic_premium"
    case truck
    case truckTraffic = "truck_traffic"
    case truckTrafficPremium = "truck_traffic_premium"
    case bicycle
    case bikeshare
    case motorScooter = "motor_scooter"
    case motorcycle
    case pedestrian
    case lowSpeedVehicle = "low_speed_vehicle"
}
