//
// LayerId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** Canonical geocoding layer IDs. */
public enum LayerId: String, Codable, CaseIterable {
    case poi
    case address
    case street
    case country
    case macroregion
    case region
    case macrocounty
    case county
    case locality
    case localadmin
    case borough
    case neighbourhood
    case postalcode
    case coarse
}
