//
// MapMatchCostingModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public enum MapMatchCostingModel: String, Codable, CaseIterable {
    case auto
    case bus
    case taxi
    case truck
    case bicycle
    case bikeshare
    case motorScooter = "motor_scooter"
    case motorcycle
    case pedestrian
    case lowSpeedVehicle = "low_speed_vehicle"
}
