//
// MapMatchWaypointAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MapMatchWaypointAllOf: Codable, JSONEncodable, Hashable {

    /** The timestamp of the waypoint, in seconds. This can inform the map matching algorithm about when the point was measured. A UNIX timestamp, or any increasing integer sequence measuring seconds from some reference point can be used. */
    public var time: Int?

    public init(time: Int? = nil) {
        self.time = time
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
    }
}

