//
// MapMatchCostingModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MapMatchCostingModel: String, Codable, CaseIterable {
    case auto = "auto"
    case bicycle = "bicycle"
    case bus = "bus"
    case pedestrian = "pedestrian"
}
