//
// MapMatchRouteResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MapMatchRouteResponseAllOf: Codable, JSONEncodable, Hashable {

    public var linearReferences: [String]?

    public init(linearReferences: [String]? = nil) {
        self.linearReferences = linearReferences
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case linearReferences = "linear_references"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(linearReferences, forKey: .linearReferences)
    }
}

