//
// NearestRoadsCostingModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** A routing profile that determines which roads are eligible for matching (e.g. trucks probably aren&#39;t on sidewalks, so the search will snap to the nearest truck-accessible road). */
public enum NearestRoadsCostingModel: String, Codable, CaseIterable {
    case auto
    case bus
    case taxi
    case truck
    case bicycle
    case bikeshare
    case motorScooter = "motor_scooter"
    case motorcycle
    case pedestrian
    case lowSpeedVehicle = "low_speed_vehicle"
}
