//
// NearestRoadsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct NearestRoadsRequest: Codable, JSONEncodable, Hashable {
    public static let locationsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var locations: [Coordinate]
    public var costing: CostingModel?
    public var costingOptions: CostingOptions?
    public var verbose: Bool? = false

    public init(locations: [Coordinate], costing: CostingModel? = nil, costingOptions: CostingOptions? = nil, verbose: Bool? = false) {
        self.locations = locations
        self.costing = costing
        self.costingOptions = costingOptions
        self.verbose = verbose
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locations
        case costing
        case costingOptions = "costing_options"
        case verbose
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(locations, forKey: .locations)
        try container.encodeIfPresent(costing, forKey: .costing)
        try container.encodeIfPresent(costingOptions, forKey: .costingOptions)
        try container.encodeIfPresent(verbose, forKey: .verbose)
    }
}
