//
// OsrmViaWaypoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct OsrmViaWaypoint: Codable, JSONEncodable, Hashable {
    /** The distance from the start of the leg, in meters. */
    public var distanceFromStart: Double
    /** The index of the waypoint's location in the route geometry. */
    public var geometryIndex: Int
    /** The index of the associated waypoint. */
    public var waypointIndex: Int

    public init(distanceFromStart: Double, geometryIndex: Int, waypointIndex: Int) {
        self.distanceFromStart = distanceFromStart
        self.geometryIndex = geometryIndex
        self.waypointIndex = waypointIndex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case distanceFromStart = "distance_from_start"
        case geometryIndex = "geometry_index"
        case waypointIndex = "waypoint_index"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(distanceFromStart, forKey: .distanceFromStart)
        try container.encode(geometryIndex, forKey: .geometryIndex)
        try container.encode(waypointIndex, forKey: .waypointIndex)
    }
}
