//
// OsrmBaseApiResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct OsrmBaseApiResponse: Codable, JSONEncodable, Hashable {
    public enum Code: String, Codable, CaseIterable {
        case ok = "Ok"
        case invalidUrl = "InvalidUrl"
        case invalidService = "InvalidService"
        case invalidVersion = "InvalidVersion"
        case invalidOptions = "InvalidOptions"
        case invalidQuery = "InvalidQuery"
        case invalidValue = "InvalidValue"
        case noSegment = "NoSegment"
        case tooBig = "TooBig"
        case noRoute = "NoRoute"
        case noTable = "NoTable"
        case notImplemented = "NotImplemented"
        case noTrips = "NoTrips"
    }

    public var code: Code
    public var message: String?
    public var dataVersion: String?

    public init(code: Code, message: String? = nil, dataVersion: String? = nil) {
        self.code = code
        self.message = message
        self.dataVersion = dataVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case dataVersion = "data_version"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(dataVersion, forKey: .dataVersion)
    }
}
