//
// OsrmGuidanceModifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** An optional value indicating the directional change of the maneuver (further clarifying type). */
public enum OsrmGuidanceModifier: String, Codable, CaseIterable {
    case uturn
    case sharpRight = "sharp right"
    case _right = "right"
    case slightRight = "slight right"
    case straight
    case slightLeft = "slight left"
    case _left = "left"
    case sharpLeft = "sharp left"
}
