//
// PeliasSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** Our database contains info from multiple sources. These identifiers can be used to either limit search results or to determine the relevance of a result. */
public enum PeliasSource: String, Codable, CaseIterable {
    case openstreetmap
    case openaddresses
    case whosonfirst
    case geonames
}
