//
// Point.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** A point geometry. */
public struct Point: Codable, JSONEncodable, Hashable {
    public static let coordinatesRule = ArrayRule(minItems: 2, maxItems: 2, uniqueItems: false)
    public var coordinates: [Double]
    public var type: String

    public init(coordinates: [Double], type: String) {
        self.coordinates = coordinates
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case coordinates
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(coordinates, forKey: .coordinates)
        try container.encode(type, forKey: .type)
    }
}
