//
// Precision.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** The level of precision for the geometry. */
public enum Precision: String, Codable, CaseIterable {
    case point
    case centroid
}
