//
// ReverseQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct ReverseQuery: Codable, JSONEncodable, Hashable {
    public static let pointLatRule = NumericRule<Double>(minimum: -90, exclusiveMinimum: false, maximum: 90, exclusiveMaximum: false, multipleOf: nil)
    public static let pointLonRule = NumericRule<Double>(minimum: -180, exclusiveMinimum: false, maximum: 180, exclusiveMaximum: false, multipleOf: nil)
    /** The latitude of the point at which to perform the search. */
    public var pointLat: Double?
    /** The longitude of the point at which to perform the search. */
    public var pointLon: Double?
    /** The radius of the circle (in kilometers) to limit the search to. Defaults to 50km if unspecified. */
    public var boundaryCircleRadius: Double?
    /** A list of country codes in ISO 3116-1 alpha-2 or alpha-3 format. */
    public var boundaryCountry: [String]?
    /** The GID of an area to limit the search to. */
    public var boundaryGid: String?
    /** A list of layers to limit the search to. */
    public var layers: [GeocodingLayer]?
    /** A list of sources to limit the search to. */
    public var sources: [GeocodingSource]?
    /** The maximum number of results to return. */
    public var size: Int?
    /** A BCP47 language tag which specifies a preference for localization of results. By default, results are in the default locale of the source data, but specifying a language will attempt to localize the results. Note that while a `langtag` (in RFC 5646 terms) can contain script, region, etc., only the `language` portion, an ISO 639 code, will be considered. So `en-US` and `en-GB` will both be treated as English. */
    public var lang: String?

    public init(pointLat: Double? = nil, pointLon: Double? = nil, boundaryCircleRadius: Double? = nil, boundaryCountry: [String]? = nil, boundaryGid: String? = nil, layers: [GeocodingLayer]? = nil, sources: [GeocodingSource]? = nil, size: Int? = nil, lang: String? = nil) {
        self.pointLat = pointLat
        self.pointLon = pointLon
        self.boundaryCircleRadius = boundaryCircleRadius
        self.boundaryCountry = boundaryCountry
        self.boundaryGid = boundaryGid
        self.layers = layers
        self.sources = sources
        self.size = size
        self.lang = lang
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pointLat = "point.lat"
        case pointLon = "point.lon"
        case boundaryCircleRadius = "boundary.circle.radius"
        case boundaryCountry = "boundary.country"
        case boundaryGid = "boundary.gid"
        case layers
        case sources
        case size
        case lang
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pointLat, forKey: .pointLat)
        try container.encodeIfPresent(pointLon, forKey: .pointLon)
        try container.encodeIfPresent(boundaryCircleRadius, forKey: .boundaryCircleRadius)
        try container.encodeIfPresent(boundaryCountry, forKey: .boundaryCountry)
        try container.encodeIfPresent(boundaryGid, forKey: .boundaryGid)
        try container.encodeIfPresent(layers, forKey: .layers)
        try container.encodeIfPresent(sources, forKey: .sources)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(lang, forKey: .lang)
    }
}
