//
// RoadClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Class of road (ranked in descending order) */
public enum RoadClass: String, Codable, CaseIterable {
    case motorway = "motorway"
    case trunk = "trunk"
    case primary = "primary"
    case secondary = "secondary"
    case tertiary = "tertiary"
    case unclassified = "unclassified"
    case residential = "residential"
    case serviceOther = "service_other"
}
