//
// RouteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct RouteResponse: Codable, JSONEncodable, Hashable {
    /** An identifier to disambiguate requests (echoed by the server). */
    public var id: String?
    public var trip: RouteTrip
    public var alternates: [RouteResponseAlternatesInner]?

    public init(id: String? = nil, trip: RouteTrip, alternates: [RouteResponseAlternatesInner]? = nil) {
        self.id = id
        self.trip = trip
        self.alternates = alternates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case trip
        case alternates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(trip, forKey: .trip)
        try container.encodeIfPresent(alternates, forKey: .alternates)
    }
}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RouteResponse: Identifiable {}
