//
// RouteTrip.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct RouteTrip: Codable, JSONEncodable, Hashable {
    /** The response status code */
    public var status: Int
    /** The response status message */
    public var statusMessage: String
    public var units: RoutingLongUnits
    public var language: RoutingLanguages
    public var locations: [RoutingResponseWaypoint]
    public var legs: [RouteLeg]
    public var summary: RouteSummary

    public init(status: Int, statusMessage: String, units: RoutingLongUnits, language: RoutingLanguages, locations: [RoutingResponseWaypoint], legs: [RouteLeg], summary: RouteSummary) {
        self.status = status
        self.statusMessage = statusMessage
        self.units = units
        self.language = language
        self.locations = locations
        self.legs = legs
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case statusMessage = "status_message"
        case units
        case language
        case locations
        case legs
        case summary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(statusMessage, forKey: .statusMessage)
        try container.encode(units, forKey: .units)
        try container.encode(language, forKey: .language)
        try container.encode(locations, forKey: .locations)
        try container.encode(legs, forKey: .legs)
        try container.encode(summary, forKey: .summary)
    }
}
