//
// SearchBulkQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct SearchBulkQuery: Codable, JSONEncodable, Hashable {
    public enum Endpoint: String, Codable, CaseIterable {
        case slashV1SlashSearch = "/v1/search"
    }

    public var endpoint: Endpoint?
    public var query: SearchQuery?

    public init(endpoint: Endpoint? = nil, query: SearchQuery? = nil) {
        self.endpoint = endpoint
        self.query = query
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpoint
        case query
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(endpoint, forKey: .endpoint)
        try container.encodeIfPresent(query, forKey: .query)
    }
}
