//
// ShapeFormat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** Specifies the precision of an encoded polyline. */
public enum ShapeFormat: String, Codable, CaseIterable {
    case polyline6
    case polyline5
}
