//
// SourceId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** Canonical geocoding source IDs. */
public enum SourceId: String, Codable, CaseIterable {
    case openstreetmap
    case openaddresses
    case whosonfirst
    case geonames
    case foursquare
}
