//
// SourceAttribution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct SourceAttribution: Codable, JSONEncodable, Hashable {
    public var fixitUrl: String?
    public var source: String
    public var sourceId: String

    public init(fixitUrl: String? = nil, source: String, sourceId: String) {
        self.fixitUrl = fixitUrl
        self.source = source
        self.sourceId = sourceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fixitUrl = "fixit_url"
        case source
        case sourceId = "source_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fixitUrl, forKey: .fixitUrl)
        try container.encode(source, forKey: .source)
        try container.encode(sourceId, forKey: .sourceId)
    }
}
