//
// TimeConstraintV1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** Specifies the time context for time-dependent routing (e.g., to account for traffic patterns or time-based access restrictions). Defaults \&quot;now\&quot; for traffic-influenced routing profiles like &#x60;auto_traffic&#x60;. */
public struct TimeConstraintV1: Codable, JSONEncodable, Hashable {
    public enum ModelType: Int, Codable, CaseIterable {
        case _0 = 0
        case _1 = 1
        case _2 = 2
    }

    /** The type of time constraint: 0 = current time (depart now), 1 = depart at the specified time, 2 = arrive by the specified time. */
    public var type: ModelType
    /** The date and time in `YYYY-MM-DDTHH:MM` format (seconds are accepted, but will be ignored). The date and time are local (civil) time as observed at the location. Required for types 1 and 2. Must not be provided for type 0. */
    public var value: String?

    public init(type: ModelType, value: String? = nil) {
        self.type = type
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(value, forKey: .value)
    }
}
