//
// TraceAttributesRequestAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct TraceAttributesRequestAllOf: Codable, JSONEncodable, Hashable {
    public var filters: TraceAttributesRequestAllOfFilters?

    public init(filters: TraceAttributesRequestAllOfFilters? = nil) {
        self.filters = filters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filters, forKey: .filters)
    }
}
