//
// TraceAttributesRequestAllOfFilters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** If present, provides either a whitelist or a blacklist of keys to include/exclude in the response. This key is optional, and if omitted from the request, all available info will be returned. */
public struct TraceAttributesRequestAllOfFilters: Codable, JSONEncodable, Hashable {
    public enum Action: String, Codable, CaseIterable {
        case include
        case exclude
    }

    public var attributes: [TraceAttributeKey]
    /** Determines whether the list of attributes will be used as a whitelist or a blacklist. */
    public var action: Action

    public init(attributes: [TraceAttributeKey], action: Action) {
        self.attributes = attributes
        self.action = action
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
        case action
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attributes, forKey: .attributes)
        try container.encode(action, forKey: .action)
    }
}
