//
// Traversability.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The directions in which the edge is traversable. */
public enum Traversability: String, Codable, CaseIterable {
    case forward = "forward"
    case backward = "backward"
    case both = "both"
}
