//
// TravelMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TravelMode: String, Codable, CaseIterable {
    case drive = "drive"
    case pedestrian = "pedestrian"
    case bicycle = "bicycle"
    case transit = "transit"
}
