//
// TzResponseV2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct TzResponseV2: Codable, JSONEncodable, Hashable {
    /** The canonical time zone ID.  In the event that multiple time zones could be returned, the first one from the Unicode CLDR timezone.xml is returned. */
    public var tzId: String
    /** The total offset, in seconds, from UTC that is currently in effect for this time zone.  This accounts for both the standard offset and any seasonal adjustments (e.g. DST). */
    public var utcOffset: Int
    /** Whether Daylight Saving Time (or a similar seasonal offset) is in effect at the queried timestamp. */
    public var isDst: Bool
    /** Integer non-leap seconds since January 1, 1970 (UNIX timestamp).  If present, offsets will be calculated as of this time. Otherwise, offsets will be effective as of the time of the query. */
    public var timestamp: Int64
    /** The local time expressed as an RFC 2822 timestamp (e.g. Tue, 1 Jun 2003 10:52:37 -0500).  If a timestamp is included in the request, it will be localized here. Otherwise, this will reflect the time of the request.  NOTE: RFC 2822 is more restrictive than other formats and cannot represent all dates. */
    public var localRfc2822Timestamp: String?
    /** The local time expressed as an RFC 3339 (ISO 8601) timestamp (e.g. 2003-06-01T10:52:37+02:00).  If a timestamp is included in the request, it will be localized here. Otherwise, this will reflect the time of the request. */
    public var localRfc3339Timestamp: String

    public init(tzId: String, utcOffset: Int, isDst: Bool, timestamp: Int64, localRfc2822Timestamp: String? = nil, localRfc3339Timestamp: String) {
        self.tzId = tzId
        self.utcOffset = utcOffset
        self.isDst = isDst
        self.timestamp = timestamp
        self.localRfc2822Timestamp = localRfc2822Timestamp
        self.localRfc3339Timestamp = localRfc3339Timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tzId = "tz_id"
        case utcOffset = "utc_offset"
        case isDst = "is_dst"
        case timestamp
        case localRfc2822Timestamp = "local_rfc_2822_timestamp"
        case localRfc3339Timestamp = "local_rfc_3339_timestamp"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tzId, forKey: .tzId)
        try container.encode(utcOffset, forKey: .utcOffset)
        try container.encode(isDst, forKey: .isDst)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(localRfc2822Timestamp, forKey: .localRfc2822Timestamp)
        try container.encode(localRfc3339Timestamp, forKey: .localRfc3339Timestamp)
    }
}
