//
// WofContextComponent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct WofContextComponent: Codable, JSONEncodable, Hashable {
    public var abbreviation: String?
    /** A globally unique identifier for a feature. Note: these are not stable for all datasets! For example, OSM features may be deleted and re-added with a new ID. Others like Who's on First guarantee stability long term. */
    public var gid: String
    public var name: String

    public init(abbreviation: String? = nil, gid: String, name: String) {
        self.abbreviation = abbreviation
        self.gid = gid
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case abbreviation
        case gid
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(abbreviation, forKey: .abbreviation)
        try container.encode(gid, forKey: .gid)
        try container.encode(name, forKey: .name)
    }
}
